[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_usd_oracle = "A2SrqZUseNK5VN3ZTEkKoWWzsyYzidCobkLfZCJ397QN"
token_minter = "7mpVgKnX25rU1Y4Sx7UN3zAK3cXv392rYNJ8X755Q2sn"

[programs.localnet]
sol_usd_oracle = "A2SrqZUseNK5VN3ZTEkKoWWzsyYzidCobkLfZCJ397QN"
token_minter = "7mpVgKnX25rU1Y4Sx7UN3zAK3cXv392rYNJ8X755Q2sn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
